---
title: "nba2017-stats-dictionary"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

player - name of player (character)
games_played - # games played by player (numeric)
minutes - total minutes played (numeric)
field_goals_made - total field goals made (numeric)
field_goals_atts - attempted field goals (numeric)
field_goals_perc - percentage of total field goals made (numeric)
points3_made - number of 3 pointers made (numeric)
points3_atts - number of 3 pointers attempted (numeric)
points3_perc - percentage of 3 pointers made (numeric)
points2_made - number of 2 pointers made (numeric)
points2_atts - number of 2 pointers attempted (numeric)
points2_perc - percentage of 2 pointers made (numeric)
points1_made - number of 1 pointers made (numeric)
points1_atts - number of 1 pointers attempted (numeric)
points1_perc - percentage of 1 pointers made (numeric)
off_rebounds - number of offensive rebounds (numeric)
def_rebounds - number of defensive rebounds (numeric)
assists - total number of assists (numeric)
steals - total number of steals (numeric)
blocks - total number of blocks (numeric)
turnovers - total number of turnovers (numeric)
fouls - total number of fouls (numeric)